In [ ]:
Ejecrcicio.-1 Crear una matriz de tranformacion homogenea 
Genera una tranformacion que represente una traslacion de (3, 2, 1) y una rotacion de 90° alrededor de eje Z

In [1]:
import numpy as np 
def matriz_transformacion(tx, ty, tz, RZ_deg): 
    theta = np.radians(RZ_deg)
    RZ = np.array([
    [np.cos(theta), -np.sin(theta), 0],
    [np.sin(theta),  np.cos(theta), 0],
    [0, 0, 1]
    ])
    T= np.array([[1, 0, 0, tx],
               [0, 1, 0, ty],
               [0, 0, 1, tz],
               [0, 0, 0, 1]]
               )
    return T

T= matriz_transformacion(3, 2, 1, 90)
print(T)

[[1 0 0 3]
 [0 1 0 2]
 [0 0 1 1]
 [0 0 0 1]]


In [ ]:
Reto Cambia el codigo para aceptar rotaciones en X, Y, Z

In [33]:
def matriz_transformacionX(tx, ty, tz, RX_deg): 
    theta = np.radians(RX_deg)
   
    RX = np.array([
    [1, 0, 0],
    [0,  np.cos(theta), -np.sin(theta)],
    [0, np.sin(theta), np.cos(theta)]
    ])
    X= np.array([
               [1, 0, 0, tx],
               [0, 1, 0, ty],
               [0, 0, 1, tz],
               [0, 0, 0, 1]]
               )
    return X
    
def matriz_transformacionY(Tx, Ty, Tz, RY_deg): 
    theta = np.radians(RY_deg)
    RY = np.array([
    [np.cos(theta), 0, np.sin(theta)],
    [0, 1, 0],
    [-np.sin(theta), 0, np.cos(theta)]
    ])
    Y = np.array([
               [1, 0, 0, Tx],
               [0, 1, 0, Ty],
               [0, 0, 1, Tz],
               [0, 0, 0, 1]]
               )
    return Y
    
def matriz_transformacionZ(tx, ty, tz, RZ_deg): 
    theta = np.radians(RZ_deg) 
    RZ = np.array([
    [np.cos(theta), -np.sin(theta), 0],
    [np.sin(theta),  np.cos(theta), 0],
    [0, 0, 1]
    ])
    Z = np.array([
               [1, 0, 0, tx],
               [0, 1, 0, ty],
               [0, 0, 1, tz],
               [0, 0, 0, 1]]
               )
    return Z
    
X= matriz_transformacionX(3, 2, 1, 90)
Y= matriz_transformacionY(3, 2, 1, 90)
Z= matriz_transformacionZ(3, 2, 1, 90)
RZ = matriz_transformacionZ(3, 2, 1, 90)
print(X, RX, "\n")
print(Y, "\n")
print(Z, "\n")

[[1 0 0 3]
 [0 1 0 2]
 [0 0 1 1]
 [0 0 0 1]] [[1 0 0 3]
 [0 1 0 2]
 [0 0 1 1]
 [0 0 0 1]] 

[[1 0 0 3]
 [0 1 0 2]
 [0 0 1 1]
 [0 0 0 1]] 

[[1 0 0 3]
 [0 1 0 2]
 [0 0 1 1]
 [0 0 0 1]] 



In [ ]:
Ejercicio .-2 Apliar una tranformacion a un punto
Tranforma el punto (1,0,0) usando la matriz homogenea del ejercicio anterior

In [5]:
punto = np.array([1, 0, 0, 1]) #Coordenadas homogeneas
punto_transformado =  T @ punto # Multiplixcaion de matrices
print("Punto Transformado:", punto_transformado[:3]) #Slicing

Punto Transformado: [4 2 1]


In [ ]:
Reto: Aplicar varias tranformaciones encadenadas

Notas:
PARA MATRICES DE ROTACION LA TRANPUERTA ES IGUAL A SU INVERSA
LA TRANPUESTA DE UNA MATRIZ SE OPTINE INTERCAMBIANDO SUS FILAS POR SUS COLUMNAS

In [ ]:
Ejercicio .-3 Inversa de una tranfromacion homogenea
Calcular la inversa de T y verificar que T * T^-1 sea la matriz identidad

In [10]:
def inversa_transformacion(T):
    R = T[0:3, 0:3]
    P = T[0:3, 3]
    T_inv = np.eye(4)
    T_inv[0:3, 0:3] = R.T
    T_inv[0:3, 3] = -R.T @ P
    return T_inv
    
T_inv = inversa_transformacion(T)
print ("Inversa de T: \n", T_inv)
print("Producto T * T^-1 \n", T @ T_inv)


Inversa de T: 
 [[ 1.  0.  0. -3.]
 [ 0.  1.  0. -2.]
 [ 0.  0.  1. -1.]
 [ 0.  0.  0.  1.]]
Producto T * T^-1 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
Reto; Implementar esta funcion para un conjunto de transformaciones almacenada en una lista

In [1]:
import numpy as np

def inversa_transformacion(T):
    #Calcula la inversa de una transformación homogénea 4x4
    R = T[0:3, 0:3]
    P = T[0:3, 3]
    T_inv = np.eye(4)
    T_inv[0:3, 0:3] = R.T
    T_inv[0:3, 3] = -R.T @ P
    return T_inv

def inversas_lista(transformaciones):
    #Calcula la inversa de un conjunto de transformaciones almacenadas en una lista.
    inversas = []
    for i, T in enumerate(transformaciones):
        T_inv = inversa_transformacion(T)
        inversas.append(T_inv)
        print(f"Transformación {i+1}:\n{T}\n")
        print(f"Inversa {i+1}:\n{T_inv}\n")
    return inversas

# Creamos algunas transformaciones 4x4 
theta1 = np.radians(45)
theta2 = np.radians(90)

Rz1 = np.array([
    [np.cos(theta1), -np.sin(theta1), 0],
    [np.sin(theta1),  np.cos(theta1), 0],
    [0, 0, 1]
])
Rz2 = np.array([
    [np.cos(theta2), -np.sin(theta2), 0],
    [np.sin(theta2),  np.cos(theta2), 0],
    [0, 0, 1]
])

T1 = np.eye(4)
T1[0:3, 0:3] = Rz1
T1[0:3, 3] = [3, 4, 0]

T2 = np.eye(4)
T2[0:3, 0:3] = Rz2
T2[0:3, 3] = [1, 2, 0]

# Lista de transformaciones
lista_T = [T1, T2]

# Calcular inversas
lista_inversas = inversas_lista(lista_T)


Transformación 1:
[[ 0.70710678 -0.70710678  0.          3.        ]
 [ 0.70710678  0.70710678  0.          4.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]

Inversa 1:
[[ 0.70710678  0.70710678  0.         -4.94974747]
 [-0.70710678  0.70710678  0.         -0.70710678]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]

Transformación 2:
[[ 6.123234e-17 -1.000000e+00  0.000000e+00  1.000000e+00]
 [ 1.000000e+00  6.123234e-17  0.000000e+00  2.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]

Inversa 2:
[[ 6.123234e-17  1.000000e+00  0.000000e+00 -2.000000e+00]
 [-1.000000e+00  6.123234e-17  0.000000e+00  1.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]

